<a href="https://colab.research.google.com/github/ersjunior/ersjunior/blob/main/Data_Risk_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


<img src='https://seeklogo.com/images/S/stone-pagamentos-logo-781DFFF629-seeklogo.com.png' width="100" height="40"/>

Este notebook foi criado para responder às perguntas do [Desafio de Data Risk Analytics](https://github.com/KormannLau/desafio-de-data-risk-analytics/blob/feat/add-doc-desafio/case_risk_analytics.md).

In [4]:
# Instalando a API do Google
!pip install gspread
!pip install gspread-dataframe

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gspread in /usr/local/lib/python3.7/dist-packages (3.4.2)
Requirement already satisfied: google-auth in /usr/local/lib/python3.7/dist-packages (from gspread) (1.35.0)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from gspread) (2.23.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread) (2022.6.15)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread) (2.10)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread) (1.24.3)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread) (0.2.8)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread) (57.4.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread) (1.15.0)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread) (4.2.4)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth->gspread) (0.4.8)
Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: gspread-dataframe in /usr/local/lib/python3.7/dist-packages (3.0.8)
Requirement already satisfied: gspread>=3.0.0 in /usr/local/lib/python3.7/dist-packages (from gspread-dataframe) (3.4.2)
Requirement already satisfied: pandas>=0.14.0 in /usr/local/lib/python3.7/dist-packages (from gspread-dataframe) (1.3.5)
Requirement already satisfied: google-auth in /usr/local/lib/python3.7/dist-packages (from gspread>=3.0.0->gspread-dataframe) (1.35.0)
Requirement already satisfied: requests>=2.2.1 in /usr/local/lib/python3.7/dist-packages (from gspread>=3.0.0->gspread-dataframe) (2.23.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.14.0->gspread-dataframe) (2022.1)
Requirement already satisfied: numpy>=1.17.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.14.0->gspread-dataframe) (1.21.6)
Requirement already satisfied: python-dateutil>=2.7.3 in /usr/local/lib/python3.7/dist-packages (from pandas>=0.14.0->gspread-dataframe) (2.8.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.7/dist-packages (from python-dateutil>=2.7.3->pandas>=0.14.0->gspread-dataframe) (1.15.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (1.24.3)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (2.10)
Requirement already satisfied: chardet<4,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests>=2.2.1->gspread>=3.0.0->gspread-dataframe) (2022.6.15)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread>=3.0.0->gspread-dataframe) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread>=3.0.0->gspread-dataframe) (0.2.8)
Requirement already satisfied: cachetools<5.0,>=2.0.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread>=3.0.0->gspread-dataframe) (4.2.4)
Requirement already satisfied: setuptools>=40.3.0 in /usr/local/lib/python3.7/dist-packages (from google-auth->gspread>=3.0.0->gspread-dataframe) (57.4.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.7/dist-packages (from pyasn1-modules>=0.2.1->google-auth->gspread>=3.0.0->gspread-dataframe) (0.4.8)

In [12]:
# Import bibliotecas
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import gspread
from gspread_dataframe import get_as_dataframe, set_with_dataframe
from google.colab import auth
auth.authenticate_user()  # Verificação da conta para leituras dos dados
from google.auth import default
creds, _ = default()
gc = gspread.authorize(creds)

In [16]:
# Criando DF para base recebida

base_stone = gc.open("Base_Stone").sheet1  # Para abrir a planilha do drive
dados = base_stone.get_all_values()  # Pegando os dados da planilha
df_base = pd.DataFrame(dados)
df_base

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,Número do Cliente,MCC,Data Apuração,Data de Entrada do Cliente,Canal,Cidade,Volume Transacionado,Quantidade de Transações,Net MDR,Aluguel,Pre-pagamento,Total,Pre-pagamento,Equipamento/Logística,Comissões,Transacionais,Outros,Total,Margem final
1,100910138884288,5309,10/1/2016,1/7/2016,Canal 3,Niterói,189.012,2.235,122,74,-,196,-,- 141,-,- 143,- 46,- 331,- 134
2,100101693498007,5963,10/1/2016,12/10/2015,Canal 3,Rio de Janeiro,-,-,-,-,-,-,-,- 13,-,-,-,- 13,- 13
3,100990966870135,5814,10/1/2016,3/29/2016,Canal 3,Rio de Janeiro,240.923,1.190,1.149,143,4.317,5.610,- 1.526,- 312,-,- 109,- 146,- 2.093,3.517
4,100112746462403,7230,10/1/2016,7/26/2016,Canal 3,Niterói,-,-,-,-,-,-,-,-,-,-,- 24,- 24,- 24
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12452,100844518929288,5661,2/1/2017,1/4/2017,Canal 3,São Paulo,-,-,-,-,-,-,-,- 14,-,-,-,- 14,- 14
12453,100858063287119,5812,2/1/2017,1/4/2017,Canal 3,Belo Horizonte,9.290,192,48,-,58,106,- 20,- 250,-,- 12,- 84,- 367,- 261
12454,100937318440605,5812,2/1/2017,11/3/2016,Canal 3,Niterói,14.523,207,174,141,159,474,- 41,- 20,-,- 12,-,- 73,401
12455,100854761191043,5732,2/1/2017,1/4/2017,Canal 3,São Paulo,12.263,53,142,-,-,142,-,- 47,-,- 4,- 61,- 112,31
12456,100828905749205,5211,2/1/2017,11/4/2016,Canal 3,São Paulo,13.427,14,122,55,573,750,- 191,- 17,-,- 2,- 68,- 279,472